### ISSUE TITLE
Repo with Demo project?

### ISSUE THREAD

**Issue by JasonLandbridge** [aalitor/AltoMultiThreadDownloadManager#1]
Hi there, 

I am interested in using this but before I'm going to integrate this in my application, I would first like to test if this works with my usecase. In the ReadMe you have a nice demo application, could you put that in a repository for others to use?

Thanks!

**Comment by aalitor** [comment]
Hi @JasonLandbridge ,

I have added a Demo project on your request but not the demo you requested, a simpler one. Check if you are still interested. https://github.com/aalitor/Alto-Download-Manager
