### ISSUE TITLE
Can you put a demo source code to Github?

### ISSUE THREAD

**Issue by hlm750908** [aalitor/AltoMultiThreadDownloadManager#3]
Excuse me!
Can you put a demo source code to Github?
After reading your instructions, I am still not sure if I can use your component correctly.
Because I don't know much about multithreading.
Including AltoHttp and AltoMultiThreadDownloadManager
Now there is a work thing more urgent, too late to fill the technical shortcomings of multithreading

**Comment by hlm750908** [comment]
using AltoMultiThreadDownloadManager;
using AltoMultiThreadDownloadManager.EventArguments;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace AltoMultiThreadDownloadManagerDemo
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        private void button1_Click(object sender, EventArgs e)
        {
            Thread th1 = new Thread(new ThreadStart(go));
            th1.Start();
        }

        private void go()
        {
            string url = "http://47.101.15345:8088/softupdate/updatetest/d78cef254b0beac670cc02594323d7ff.rar";
            string finalFilePath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop)+"\\"+ Path.GetFileName(url);
            string directoryForChunks = "";
            int nofMaxThread=5;
            var dorg = new MultiThreadDownloadOrganizer(url, finalFilePath, directoryForChunks, nofMaxThread);
            dorg.ProgressChanged += dorg_ProgressChanged;
            dorg.Completed += dorg_Completed;
            button1.Invoke(new Action<string>(ok), "Download start");
            dorg.Start();
        }

        private void dorg_ProgressChanged(object sender, AltoMultiThreadDownloadManager.EventArguments.ProgressChangedEventArgs e)
        {
            progressBar1.Invoke(new Action<int>(setNow),(int) e.Progress);
        }

        private void dorg_Completed(object sender, EventArgs e)
        {
            button1.Invoke(new Action<string>(ok), "Download Completed");
        }

        void ok(string str)
        {
            button1.Text = str;
        }

        void setNow(int i)
        {
            progressBar1.Value = i;

        }
      
    }
}

**Comment by aalitor** [comment]
Hi @hlm750908,

In your code you definitely must set `directoryForChunks` to a folder. This is a folder path to store partial contents and then these partial contents will be merged at final into the `finalFilePath ` and then will be deleted after merging finished.
Also you don't need a thread for the method `go`. `dorg.Start` is a thread works async already.

```
private void go()
    {
        string url = "http://47.101.15345:8088/softupdate/updatetest/d78cef254b0beac670cc02594323d7ff.rar";
        string finalFilePath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop)+"\\"+ Path.GetFileName(url);
        //This folder must be set
        string directoryForChunks = Environment.GetFolderPath(Environment.SpecialFolder.AppData);
        int nofMaxThread=5;
        var dorg = new MultiThreadDownloadOrganizer(url, finalFilePath, directoryForChunks, nofMaxThread);
        dorg.ProgressChanged += dorg_ProgressChanged;
        dorg.Completed += dorg_Completed;
        //This event should be checked to be sure download and merging progress are both completed
        dorg.MergingCompleted += dorg_MergingCompleted;
        button1.Invoke(new Action<string>(ok), "Download start");
        dorg.Start();
    }
```

**Comment by aalitor** [comment]
I have updated README with more detailed demo. I can't access your url using browser or code. You may check the url for any mistake.

**Comment by aalitor** [comment]
Hi again @hlm750908 ,

I have added repo to be more clear. Check it please at https://github.com/aalitor/Alto-Download-Manager
